// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgDGEziQ8OrL81HbBi25CNiNCiIACUVPI',
    appId: '1:433999419050:web:4b9e354584b25aec4f22d3',
    messagingSenderId: '433999419050',
    projectId: 'whatsapp-project-bff31',
    authDomain: 'whatsapp-project-bff31.firebaseapp.com',
    storageBucket: 'whatsapp-project-bff31.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdZD64C6i8kWZb7GT_Dm2JY1GFgpX81i8',
    appId: '1:433999419050:android:22a7eda8f97899f64f22d3',
    messagingSenderId: '433999419050',
    projectId: 'whatsapp-project-bff31',
    storageBucket: 'whatsapp-project-bff31.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADhxK5PEN8XGHV5KaRby-MO1spfGH1tvI',
    appId: '1:433999419050:ios:b02cd9d3d1e6c3254f22d3',
    messagingSenderId: '433999419050',
    projectId: 'whatsapp-project-bff31',
    storageBucket: 'whatsapp-project-bff31.appspot.com',
    iosClientId: '433999419050-ph5k7mr22elnrlami7k7hdruad3kcc63.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappUi',
  );
}
